spring.application.name=xchange
# ===============================
# MYSQL CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/xchange_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# Put your MySQL password here
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate logic
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# MONGODB CONFIGURATION
# ===============================
# Default local port for Mongo is 27017
spring.data.mongodb.uri=mongodb://localhost:27017/xchange_db